name: SCA - skan zależności
on: [pull_request]
jobs:
  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # pobierz kod
      - uses: snyk/actions/node@master # uruchom Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
